# Generated by Django 3.2 on 2022-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-created'], 'verbose_name': 'камментарий', 'verbose_name_plural': 'каментарии'},
        ),
        migrations.AddField(
            model_name='coment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
