# Generated by Django 3.2 on 2022-04-02 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_auto_20220402_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='name',
        ),
        migrations.AddField(
            model_name='coment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор каментарии'),
        ),
    ]
