# Generated by Django 3.2 on 2022-04-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulartour',
            name='status',
            field=models.CharField(choices=[('waiting', 'идет набор'), ('start', 'начался'), ('completed', 'завершен'), ('rejected', 'отменен')], default='waiting', max_length=10, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_count', models.PositiveSmallIntegerField(verbose_name='место')),
                ('mobile', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('finished', 'Завершен'), ('rejected', 'Отменен')], default='new', max_length=11, verbose_name='Номер телефона')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачено')),
                ('notice', models.CharField(blank=True, max_length=250, null=True, verbose_name='Допю инфо')),
                ('status', models.CharField(max_length=11, verbose_name='статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('regular_tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tours.regulartour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'ordering': ['-created'],
            },
        ),
    ]
